config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :user
  resources :lists
  resources :tasks
  
  
  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  
  validates :name, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  # call the configured params 
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  # protect the database, while allowing these fields to be updated.
  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
  
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all.where("user_id = ?", current_user.id)
  end
  
  def show
    @list = List.find(params[:id])
    @tasks = Task.all.where("list_id = ?", @list.id)
  end
  
  def new
    @list = List.new
  end
  
  def create
    @list = List.create(params[:list].permit(:name))
    @list.finished = false
    @list.user_id = current_user.id
    
    if @list.save
      redirect_to task_path(@list.id), :notice => "A new list has been successfully created"  
    else
      render "new"
    end
  end
  
  def edit
    @list = List.find(params[:id])
    
    respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @task }
    end
  end
  
  def update
    @list = List.find(params[:id])
    @list.finished = true
    if @list.update_attributes(params[:list].permit(:finished, :name))
        redirect_to lists_path
    else
        render "new"
    end
  end
  
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, :notice => "Your list has been deleted"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def new
        @task = Task.new
        @task.list_id = params[:list_id]
        
        respond_to do |format|
            format.html # new.html.erb
            format.xml  { render :xml => @task }
        end
    end
    
    def create
        @task = Task.create(params[:task].permit(:content, :list_id, :image))
        @task.finished = false
        
        if @task.save
          redirect_to task_path(@task.list_id), :notice => "A new list has been successfully created"  
        else
          render "new"
        end
    end
    
    def show
        @list = List.find(params[:id])
        @tasks = Task.all.where("list_id = ?", @list.id)
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to task_path(@task.list_id), :notice => "Your task has been deleted"
    end
    
    def edit
        @task = Task.find(params[:id])
        
        respond_to do |format|
            format.html # new.html.erb
            format.xml  { render :xml => @task }
        end
    end
    
    def update
        @task = Task.find(params[:id])
        if @task.update_attributes(params[:task].permit(:finished, :content, :image))
            redirect_to task_path(@task.list_id)
        else
            render "new"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
   <ul class="navbar-nav mr-auto">
       <li class="nav-item">
          <h3 class="white">TO-DO LIST</h3>
       </li>
   </ul>
  <ul class="navbar-nav">
      <li class="nav-item px-1">
          <!--Domov-->
        <a href="/lists"><button class="btn btn-info" type="button"><i class="fa fa-home" aria-hidden="true"></i></button></a> 
      </li>
      <li class="nav-item px-1">
        <a><%= link_to fa_icon("plus"), new_list_path, class: "btn btn-info" %></a>
        
      </li>
      <li class="nav-item px-1">
          <!--Profile dropdown-->
          <div class="dropdown">
          <button class="btn btn-info dropdown-toggle remove-dropdown-arrow" type="button"  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-circle" aria-hidden="true"></i></button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <h6 class="dropdown-header text-center"><%= current_user.email %> (<%= current_user.username %>)</h6>
            <div class="dropdown-divider"></div>
            <%= link_to('Change password', edit_user_registration_path, class: "dropdown-item")%>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "dropdown-item")%>
          </div>
        </div>
      </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>   
  <!--Če je uporabnik prijavljen bo prikazan meni, drugače pa ne-->
    <%= render '/layouts/nav' %>
  <% end %>
  
  <div class="container mt-4">
    <%= yield %>
  </div>

</body>
</html>

app/views/lists/edit.html.erb
 <div class="h-100 row justify-content-center align-items-center mt-5"><!--Aligns div to the center-->
  <div class="col-5 text-center">
    <div class="card ">
      <div class="card-header">
        <h2>Update a list</h2>
      </div>
      <div class="card-body">
         <%= form_for @list do |l| %>
            <div class="form-group">
                <% l.label :name %><br/>
                <%= l.text_field :name, class: "form-control" %>
              </div>
            <div class="form-group">
                <span>Finished</span><br/><% l.label :finished %><br/>
                <%= l.check_box :finished, autofocus: true, class: "form-control" %>
              </div>
          <div class="form-group">
            <%= l.submit "Update", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div>
                <h5 class="text-center"><i class="fa fa-square-o" aria-hidden="true"></i><span class="ml-2"></span>To-Do Lists</h5>
                <% for @l in @lists %>
                    <% if !@l.finished %>
                        <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                          <div class="card-block tasks">
                              <div class="float-left">
                                  <%= link_to @l.name, task_path(@l.id) %>
                              </div>
                              <div class="float-right">
                                  <span class="mx-1 card-icon">
                                      <%= link_to fa_icon("check-circle"), edit_list_path(@l.id) %>
                                  </span>
                                  <span class="mx-1 card-icon">
                                      <%= link_to fa_icon("trash-o"), @l, :data => {:confirm => 'Are you sure?'}, :method => 'delete' %>
                                  </span>
                              </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <div>
                <h5 class="text-center mt-4"><i class="fa fa-check-square-o" aria-hidden="true"></i><span class="ml-2"></span>Completed</h5>
                <% for @l in @lists %>
                    <% if @l.finished %>
                        <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                          <div class="card-block tasks">
                              <div class="float-left">
                                  <%= link_to @l.name, list_path(@l.id) %>
                              </div>
                              <div class="float-right">
                                  <span class="mx-1 card-icon">
                                      <%= link_to fa_icon("trash-o"), @l, :data => {:confirm => 'Are you sure?'}, :method => 'delete' %>
                                  </span>
                              </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</div>

app/views/lists/new.html.erb
<div class="h-100 row justify-content-center align-items-center mt-5"><!--Aligns div to the center-->
  <div class="col-5 text-center">
    <div class="card ">
      <div class="card-header">
        <h2>Create a List</h2>
      </div>
      <div class="card-body">
        <%= form_for @list do |l| %>
        
          <div class="form-group">
            <%= l.label :name %><br />
            <%= l.text_field :name, autofocus: true, class: 'form-control' %>
          </div>
        
          <div class="form-group">
            <%= l.submit "Create", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <h3 class="text-center"><%= @list.name %></h3>
            <div class="mt-5">
                <div class="row">
                    <div class="col-3"></div>
                    <div class="col-6 p-3">
                        <h5 class="text-center">Unfinished Tasks</h5>
                        <% for @t in @tasks %>
                            <% if !@t.finished %>
                                <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                                  <div class="card-block tasks">
                                      <div>
                                          <% if @t.image.present? %>
                                            <%= image_tag @t.image_url.to_s, class: "medium-input" %>
                                          <% end %>
                                      </div>
                                      <div class="float-left">
                                          <span class="task-content"><%= @t.content %></span>
                                      </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                        <h5 class="text-center mt-4">Finished Tasks</h5>
                        <% for @t in @tasks %>
                            <% if @t.finished %>
                                <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                                  <div class="card-block tasks">
                                      <div>
                                          <% if @t.image.present? %>
                                            <%= image_tag @t.image_url.to_s, class: "medium-input" %>
                                          <% end %>
                                      </div>
                                      <div class="float-left">
                                          <span class="task-content"><%= @t.content %></span>
                                      </div>
                                      <div class="float-right">
                                      </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
                <div class="col-3"></div>
            </div>
        </div>
    </div>
</div>

app/views/page/create.html.erb
<h1>Page#create</h1>
<p>Find me in app/views/page/create.html.erb</p>

app/views/pages/home.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div>
                <h5 class="text-center"><i class="fa fa-square-o" aria-hidden="true"></i><span class="ml-2"></span>To-Do Lists</h5>
                <% for @l in @lists %>
                    <% if !@l.finished %>
                        <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                          <div class="card-block tasks">
                              <div class="float-left">
                                  <a href=""><%= @l.name %></a>
                              </div>
                              <div class="float-right">
                                  <span class="mx-1 card-icon">
                                      <a href=""><i class="fa fa-pencil"></i></a>
                                  </span>
                                  <span class="mx-1 card-icon">
                                      <a href=""><i class="fa fa-trash-o"></i></a>
                                  </span>
                              </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <div>
                <h5 class="text-center mt-4"><i class="fa fa-check-square-o" aria-hidden="true"></i><span class="ml-2"></span>Completed</h5>
                <% for @l in @lists %>
                    <% if @l.finished %>
                        <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                          <div class="card-block tasks">
                              <div class="float-left">
                                  <%= @l.name %>
                              </div>
                              <div class="float-right">
                                  <span class="mx-1 card-icon">
                                      <a href=""><i class="fa fa-trash-o"></i></a>
                                  </span>
                              </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</div>

app/views/tasks/edit.html.erb
 <div class="h-100 row justify-content-center align-items-center mt-5"><!--Aligns div to the center-->
  <div class="col-5 text-center">
    <div class="card ">
      <div class="card-header">
        <h2>Update a task</h2>
      </div>
      <div class="card-body">
         <%= form_for @task do |t| %>
            <div class="form-group">
                <% t.label :content %><br/>
                <%= t.text_field :content, class: "form-control" %>
              </div>
              <div class="form-group">
                  <%= t.file_field :image, class: "form-control" %>
              </div>
            <div class="form-group">
                <span>Finished</span><br/><% t.label :finished %><br/>
                <%= t.check_box :finished, autofocus: true, class: "form-control" %>
              </div>
          <div class="form-group">
            <%= t.submit "Update", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= form_for @task do |t| %>

  <div class="form-group">
    <%= t.label :content %><br />
    <%= t.text_field :content, autofocus: true, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= t.file_field :image, class: "form-control medium-input" %>
  </div>
  
  <div class="form-group" style="display: none">
    <%= t.text_field :list_id %>
  </div>

  <div class="form-group">
    <%= t.submit "Create", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <h3 class="text-center"><%= @list.name %></h3>
            <div class="mt-5">
                <div class="row">
                    <div class="col-3"></div>
                    <div class="col-6 p-3">
                        <h5 class="text-center">Unfinished Tasks</h5>
                        <% for @t in @tasks %>
                            <% if !@t.finished %>
                                <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                                  <div class="card-block tasks">
                                      <div>
                                          <% if @t.image.present? %>
                                            <%= image_tag @t.image_url.to_s, class: "medium-input" %>
                                          <% end %>
                                      </div>
                                      <div class="float-left">
                                        <span class="task-content"><%= @t.content %></span>
                                      </div>
                                      <div class="float-right">
                                          <span class="mx-1 card-icon">
                                              <%= link_to fa_icon("check-circle"), edit_task_path(@t.id) %>
                                          </span>
                                          <span class="mx-1 card-icon">
                                              <%= link_to fa_icon("trash-o"), @t, :data => {:confirm => 'Are you sure?'}, :method => 'delete' %>
                                          </span>
                                      </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                        <%= link_to "Add Task", new_task_path(:list_id => @list.id), class: "btn btn-primary mt-3" %>
                        <h5 class="text-center mt-4">Finished Tasks</h5>
                        <% for @t in @tasks %>
                            <% if @t.finished %>
                                <div class="card col-12 mt-3 p-3 card-no-border card-dark-border">
                                  <div class="card-block tasks">
                                      <div>
                                          <% if @t.image.present? %>
                                            <%= image_tag @t.image_url.to_s, class: "medium-input" %>
                                          <% end %>
                                      </div>
                                      <div class="float-left">
                                          <span class="task-content"><%= @t.content %></span>
                                      </div>
                                      <div class="float-right">
                                          <span class="mx-1 card-icon">
                                              <%= link_to fa_icon("trash-o"), @t, :data => {:confirm => 'Are you sure?'}, :method => 'delete' %>
                                          </span>
                                      </div>
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                </div>
                <div class="col-3"></div>
            </div>
        </div>
    </div>
</div>